### ISSUE TITLE
计算课程数据时发生错误 原因 Unexpected character encountered while parsing value: i. Path '', line 0

### ISSUE THREAD

**Issue by l1ta0** [xixixixixiao/mooc-downloader#19]
计算课程数据时发生错误 原因 Unexpected character encountered while parsing value: i. Path '', line 0

下载部分视频会出现这种情况
下载报错的某一个课程链接
https://mooc.study.163.com/learn/1000004000?tid=2403026002#/learn/announce

**Comment by xixixixixiao** [comment]
感谢反馈, 错误已记录, 原因是程序暂时无法处理中国大学 MOOC 中一些比较老的课程中采用的数据格式.
