### ISSUE TITLE
下载个数

### ISSUE THREAD

**Issue by luck-mao** [xixixixixiao/mooc-downloader#21]
可以增加下载个数吗，一次只能下载一个课程有点慢

**Comment by xixixixixiao** [comment]
可以, 但是没有必要. 如果增加多个课程同时下载的功能会导致有人拉取整站课程对中国大学 MOOC 服务器造成压力. 而开发这款软件的初衷是离线缓存**正在学习**的课程, 而不是下载整站课程. 希望本软件的使用者是学习资源的学习者, 而不是收集者.
