### ISSUE TITLE
程序组件“FIREFOX缺失，请重新下载

### ISSUE THREAD

**Issue by lastpass8** [xixixixixiao/mooc-downloader#22]
最新版启动这个提示
[https://s1.ax1x.com/2020/09/21/wbDlCt.png](url)

**Comment by xixixixixiao** [comment]
需要更详细的信息, 请注明运行环境的详细信息:
- 操纵系统位数.
- 操纵系统版本号.
- 是否在虚拟机环境中运行.
- CPU 型号
- 内存大小
- ...

**Comment by xixixixixiao** [comment]
![wbDlCt](https://user-images.githubusercontent.com/13077617/93755732-5d2ec080-fc36-11ea-9949-3b34cf67f47a.png)
反馈附带的截图.

此前收到过类似反馈 (#3) 报告相同的错误, 由于暂无虚拟机环境无法复现此错误, 需要更多的信息.

**Comment by lastpass8** [comment]
> ![wbDlCt](https://user-images.githubusercontent.com/13077617/93755732-5d2ec080-fc36-11ea-9949-3b34cf67f47a.png)
> 反馈附带的截图.
> 
> 此前收到过类似反馈 (#3) 报告相同的错误, 由于暂无虚拟机环境无法复现此错误, 需要更多的信息.

- 64位
- Windows 10专业版  系统 19041.508
- 实机运行
- Intel(R) Core(TM)i5-4210M CPu @ 2.60GHz 2.60 GHz 处理器∶ 
- 已安装的内存（RAM）∶ 8.00 GB（7.89 GB可用）

**Comment by xcl-net** [comment]
---------------------------
中国大学 MOOC 下载器
---------------------------
程序组件 "FIREFOX" 缺失, 请重新下载.
---------------------------
确定   
---------------------------

**Comment by xcl-net** [comment]
> ## 中国大学 MOOC 下载器
> ## 程序组件 "FIREFOX" 缺失, 请重新下载.
> ## 确定

![image](https://user-images.githubusercontent.com/15728845/100084005-2e76d580-2e85-11eb-80e8-9f3610128ef1.png)

**Comment by xcl-net** [comment]
> > ## 中国大学 MOOC 下载器
> > ## 程序组件 "FIREFOX" 缺失, 请重新下载.
> > ## 确定
> 
> ![image](https://user-images.githubusercontent.com/15728845/100084005-2e76d580-2e85-11eb-80e8-9f3610128ef1.png)

物理机运行

**Comment by xcl-net** [comment]
> > > ## 中国大学 MOOC 下载器
> > > ## 程序组件 "FIREFOX" 缺失, 请重新下载.
> > > ## 确定
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/15728845/100084005-2e76d580-2e85-11eb-80e8-9f3610128ef1.png)
> 
> 物理机运行
> 
> 直接使用Release包没问题, 但是在vs2019里启动项目后, 就报这个错误,

**下载 release 包, 把Firefox 和 ffmeg 文件夹, 拷贝到 debug目录下, 项目就能正常运行了**

**Comment by AlienXK-A** [comment]
release 包1.3.1 、1.2.1 都出现同样问题，非虚拟机，win10，杀软WINGDOWS DEFENDER，第一次运行正常可下载mooc，然后移动了软件位置，再次运行出现问题，期间用过dism
已重新下载 release 包, 完全替换了软件，并把Firefox 和 ffmeg 文件夹拷贝到了Windows/debug目录下, 但项目还是不能正常运行
请问还有救么？

**Comment by MrLonelyLovely** [comment]
我的是在mac上parallels desktop运行，也这样提示，请问下该怎么处理呢？

**Comment by xixixixixiao** [comment]
> 
> 
> 我的是在mac上parallels desktop运行，也这样提示，请问下该怎么处理呢？

换用其它电脑试试叭.
