### ISSUE TITLE
总是提示课程还未开课

### ISSUE THREAD

**Issue by syyz04** [xixixixixiao/mooc-downloader#26]
尝试了多个课程，不管是正在开课的、还是本学期确实没有开课的，输入课程地址--解析出课程-选择清晰度后，总是提示“***”还未开课。

**Comment by PyJun** [comment]
xuewuzhi.net
下载最新版



---原始邮件---
发件人: "syyz04"<notifications@github.com&gt;
发送时间: 2020年11月6日(周五) 上午9:23
收件人: "xixixixixiao/mooc-downloader"<mooc-downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [xixixixixiao/mooc-downloader] 总是提示课程还未开课 (#26)




 
尝试了多个课程，不管是正在开课的、还是本学期确实没有开课的，输入课程地址--解析出课程-选择清晰度后，总是提示“***”还未开课。
