### ISSUE TITLE
kaoyan域名下的视频无法下载

### ISSUE THREAD

**Issue by gadfly3173** [xixixixixiao/mooc-downloader#27]
课程地址：http://www.icourse163.org/learn/kaopei-1003293004?tid=1003528002#/learn/announce  
http://kaoyan.icourse163.org/course/terms/1003528002.htm?courseId=1003293004  
http://www.icourse163.org/learn/kaopei-1003299003?tid=1003524007#/learn/announce  
http://kaoyan.icourse163.org/course/terms/1003524007.htm?courseId=1003299003
![1](https://user-images.githubusercontent.com/28685179/98553753-e8ddd880-22da-11eb-8289-b589f875dd2a.png)

**Comment by PyJun** [comment]
用release下的exe文件吧


 
---原始邮件---
发件人: "猪蹄宝宝"<notifications@github.com&gt;
发送时间: 2020年11月9日 22:29:16
收件人: "xixixixixiao/mooc-downloader"<mooc-downloader@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [xixixixixiao/mooc-downloader] kaoyan域名下的视频无法下载 (#27)




 
课程地址：http://www.icourse163.org/learn/kaopei-1003293004?tid=1003528002#/learn/announce
 http://www.icourse163.org/learn/kaopei-1003299003?tid=1003524007#/learn/announce

**Comment by xixixixixiao** [comment]
本程序不对付费课程做下载支持.
