### ISSUE TITLE
已购买的考研课程无法下载，下载出来的只有命名好的文件夹

### ISSUE THREAD

**Issue by VastDale** [xixixixixiao/mooc-downloader#29]
课程链接：https://www.icourse163.org/learn/kaopei-1206579809?tid=1206908208

已购买的考研课程 跪求大佬更新 我可以提供我的慕课账号

<img width="361" alt="搜狗截图20201115005758" src="https://user-images.githubusercontent.com/74463100/99152625-dcdc8700-26dd-11eb-8d58-0a5bd7d89770.png">

**Comment by xixixixixiao** [comment]
暂时不支持考研课程下载，付费课程的下载违背本程序的开发初衷，亦即以后也不打算支持付费课程的下载。希望理解。
