### ISSUE TITLE
部分课程的部分章节,下载"错误,已取消"*5，但从log来看，地址没错。 

### ISSUE THREAD

**Issue by firleo** [xixixixixiao/mooc-downloader#34]
https://www.icourse163.org/course/NEU-1002085015?tid=1206504207
部分课程的部分章节,下载"错误,已取消"*5，但从log来看，地址没错。

**Comment by firleo** [comment]
似乎出问题的都是大文件，大概>290MB（疑似）

**Comment by xixixixixiao** [comment]
修复课程的视频的下载链接的识别.
