### ISSUE TITLE
下载课程发生错误

### ISSUE THREAD

**Issue by chenghaofan** [xixixixixiao/mooc-downloader#37]
报错 下载课程发生错误，原因：System.ArugmentNullException: Value cannot be null. Parameter name source

课程网址：https://www.icourse163.org/course/HIT-1206323802?tid=1461138442

![Ashampoo_Snap_2021 03 18_01h12m04s_001_](https://user-images.githubusercontent.com/80846731/111510231-8ca72b80-8788-11eb-8ea4-2967372374de.png)

**Comment by xixixixixiao** [comment]
感谢反馈, 已记录.

**Comment by xixixixixiao** [comment]
程序已修复, 最新版程序已支持下载.
