### ISSUE TITLE
有部分课程下载时出错

### ISSUE THREAD

**Issue by Emanresuqy** [xixixixixiao/mooc-downloader#38]
作者你好。
感谢提供这么好用的工具。我在使用过程中，遇到4门课程的链接下载出错，报错都一样

_“下载课程发生错误，原因：System.ArgumentNullException:值不能为null。参数名：source   在System.Ling.Enumerable.Select[TSource,TResult](TEnumerable`1 source,Func`2 selector)  
在MoocDownloader.App.ViewModels.MainViewModel.<>c.<DownloadCourseListAsync>b__14_0(ChapterN。。。”_

后面的信息看不到，横向进度条拖不动。

![图片](https://user-images.githubusercontent.com/32285458/111868743-9a41f880-89b6-11eb-9cb2-e4010d0b412a.png)

4门课程的链接是：
https://www.icourse163.org/learn/HLJP-1003128001?tid=1461702442
https://www.icourse163.org/learn/HUSE-1459666161?tid=1460191441
https://www.icourse163.org/learn/SEU-1003361015?tid=1450369452
https://www.icourse163.org/learn/JSJZY-1001755249?tid=1450361464

除了这4门课程，其他的经过测试正常。
下载这些课程的原因是相对于网页播放器，更习惯用potplayer观看学习。

烦请得空查看一下这些个错误的原因。

**Comment by xixixixixiao** [comment]
收到, 最近工作繁忙, 有空改进.

**Comment by xixixixixiao** [comment]
程序已修复, 最新版程序以支持以上 4 门课程下载.
