### ISSUE TITLE
最新版下载视频失败

### ISSUE THREAD

**Issue by xmhwws** [xixixixixiao/mooc-downloader#40]
链接：http://www.icourse163.org/learn/kaopei-1206583804?tid=1206901212#/learn/announce
版本：v1.3.1.1
类型：付费视频

![2021-03-26_19-49-06](https://user-images.githubusercontent.com/42903751/112627464-90424e80-8e29-11eb-91ba-333f8e60d247.png)

可提供账号密码，如果作者愿意提供联系方式

**Comment by xixixixixiao** [comment]
本程序不支持下载付费视频，未来亦不开发相应功能。
