### ISSUE TITLE
报错"程序组件 Firefox 缺失，请重新下载

### ISSUE THREAD

**Issue by hwoppoe** [xixixixixiao/mooc-downloader#41]
win10专业版 没装火狐装的chrome，不知道为啥会这样

**Comment by xixixixixiao** [comment]
1，如果你是拉取的源代码自行编译运行，在调试前需要将 Visual Studio 的模式设置为 x64。
2，仅仅使用本程序请直接从百度网盘或者发行链接中下载已经编译好的程序即可。
