### ISSUE TITLE
无法下载，运行日志提示下载视频发生错误

### ISSUE THREAD

**Issue by chenwwgit** [xixixixixiao/mooc-downloader#42]
输入课程链接https://www.icourse163.org/learn/NUDT-438002?tid=1460994443#/learn/content，设置下载保存目录，然后点开始下载后发现无法下载，运行日志显示----下载视频发生错误，原因：System.NullReferenceException：未将对象引用设置到对象的实例。

**Comment by xixixixixiao** [comment]
本程序无法下载已经关闭的课程.
