### ISSUE TITLE
下载出现异常

### ISSUE THREAD

**Issue by shoukailiang** [xixixixixiao/mooc-downloader#45]
![image](https://user-images.githubusercontent.com/24668909/113505252-2e43c080-9570-11eb-9332-136abd8295d0.png)

**Comment by shoukailiang** [comment]
https://www.icourse163.org/course/UIBE-1003113004?tid=1450405447

**Comment by xixixixixiao** [comment]
感谢反馈.

**Comment by xixixixixiao** [comment]
程序的源代码已经修改好了, 同学只需要下载文档吗? 我帮你下载好, 你下载这个附件就行了. (上传了半天没上传上来, 百度网盘分享给你.)
链接：https://pan.baidu.com/s/1en4iCHWJ6mqqWt738LO2Gw 
提取码：oe82

**Comment by shoukailiang** [comment]
好的谢谢啦~
