### ISSUE TITLE
指定的参数已超出有效值的范围。

### ISSUE THREAD

**Issue by lyf9ljh** [xixixixixiao/mooc-downloader#5]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。
https://www.icourse163.org/course/BLCU-1206308832?tid=1206620267
************** 异常文本 **************
System.ArgumentOutOfRangeException: 指定的参数已超出有效值的范围。
   在 MoocDownloader.App.ViewModels.MainViewModel.<StartDownload>d__13.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.4200.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MoocDownloader.App
    程序集版本:1.1.1.0
    Win32 版本:1.1.1.0
    基本代码:file:///F:/BaiduNetdiskDownload/MoocDownloader.1.1.1.0/MoocDownloader.App.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.4200.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.4200.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Geckofx-Core
    程序集版本:60.0.47.0
    Win32 版本:60.0.47.0
    基本代码:file:///F:/BaiduNetdiskDownload/MoocDownloader.1.1.1.0/Geckofx-Core.DLL
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.4190.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.4200.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Newtonsoft.Json
    程序集版本:12.0.0.0
    Win32 版本:12.0.3.23909
    基本代码:file:///F:/BaiduNetdiskDownload/MoocDownloader.1.1.1.0/Newtonsoft.Json.DLL
----------------------------------------
System.Net.Http
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Geckofx-Winforms
    程序集版本:60.0.47.0
    Win32 版本:60.0.47.0
    基本代码:file:///F:/BaiduNetdiskDownload/MoocDownloader.1.1.1.0/Geckofx-Winforms.DLL
----------------------------------------
HtmlAgilityPack
    程序集版本:1.11.24.0
    Win32 版本:1.11.24
    基本代码:file:///F:/BaiduNetdiskDownload/MoocDownloader.1.1.1.0/HtmlAgilityPack.DLL
----------------------------------------
MsieJavaScriptEngine
    程序集版本:3.0.7.0
    Win32 版本:3.0.7.0
    基本代码:file:///F:/BaiduNetdiskDownload/MoocDownloader.1.1.1.0/MsieJavaScriptEngine.DLL
----------------------------------------
System.Numerics
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    程序集版本:4.0.0.0
    Win32 版本:4.8.4200.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    程序集版本:4.0.0.0
    Win32 版本:4.8.4200.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。

https://www.icourse163.org/course/BLCU-1206308832?tid=1206620267

**Comment by xixixixixiao** [comment]
好的, 已收到反馈.

**Comment by xixixixixiao** [comment]
已修复, 下一个版本中包含了此项修复.
